"""Add test templates and update tests table

Revision ID: 42cbb90c7e28
Revises: 452b42b124a3
Create Date: 2025-09-22 19:06:38.371247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '42cbb90c7e28'
down_revision: Union[str, Sequence[str], None] = '452b42b124a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_templates',
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('owner_user_id', sa.String(), nullable=True),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('template_name', sa.String(), nullable=False),
    sa.Column('test_type', sa.Enum('CHAPTER_TEST', 'SUBJECT_TEST', 'FULL_MOCK', 'CUSTOM', name='testtypeenum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.chapter_id'], ),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.exam_id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ),
    sa.PrimaryKeyConstraint('template_id')
    )
    op.create_table('test_template_questions',
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=False),
    sa.Column('question_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['test_templates.template_id'], ),
    sa.PrimaryKeyConstraint('template_id', 'question_id')
    )
    op.alter_column('questions', 'question_type',
               existing_type=postgresql.ENUM('MCSC', 'MCMC', 'INT', 'NUM', name='questiontype'),
               type_=sa.Enum('MCMC', 'MCSC', 'NUMERICAL', name='questiontypeenum'),
               existing_nullable=False)
    op.alter_column('questions', 'difficulty_level',
               existing_type=postgresql.ENUM('EASY', 'MEDIUM', 'HARD', name='difficultylevel'),
               type_=sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficultylevelenum'),
               existing_nullable=False)
    op.add_column('tests', sa.Column('template_id', sa.String(), nullable=False))
    op.drop_constraint(op.f('tests_subject_id_fkey'), 'tests', type_='foreignkey')
    op.drop_constraint(op.f('tests_chapter_id_fkey'), 'tests', type_='foreignkey')
    op.create_foreign_key(None, 'tests', 'test_templates', ['template_id'], ['template_id'])
    op.drop_column('tests', 'chapter_id')
    op.drop_column('tests', 'subject_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tests', sa.Column('chapter_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tests', type_='foreignkey')
    op.create_foreign_key(op.f('tests_chapter_id_fkey'), 'tests', 'chapters', ['chapter_id'], ['chapter_id'])
    op.create_foreign_key(op.f('tests_subject_id_fkey'), 'tests', 'subjects', ['subject_id'], ['subject_id'])
    op.drop_column('tests', 'template_id')
    op.alter_column('questions', 'difficulty_level',
               existing_type=sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficultylevelenum'),
               type_=postgresql.ENUM('EASY', 'MEDIUM', 'HARD', name='difficultylevel'),
               existing_nullable=False)
    op.alter_column('questions', 'question_type',
               existing_type=sa.Enum('MCMC', 'MCSC', 'NUMERICAL', name='questiontypeenum'),
               type_=postgresql.ENUM('MCSC', 'MCMC', 'INT', 'NUM', name='questiontype'),
               existing_nullable=False)
    op.drop_table('test_template_questions')
    op.drop_table('test_templates')
    # ### end Alembic commands ###
