"""Add test templates and update tests table

Revision ID: 42cbb90c7e28
Revises: 452b42b124a3
Create Date: 2025-09-22 19:06:38.371247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '42cbb90c7e28'
down_revision: Union[str, Sequence[str], None] = '452b42b124a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Correctly upgrade schema with manual ENUM handling."""
    
    # --- Part 1: Manually handle the QuestionTypeEnum change ---
    # Alembic's autogenerate gets this wrong. This is the correct "rename and recreate" pattern.
    op.execute("ALTER TYPE questiontype RENAME TO questiontype_old")
    op.execute("CREATE TYPE questiontype AS ENUM('MCMC', 'MCSC', 'NUMERICAL')")
    op.execute(
        "ALTER TABLE questions ALTER COLUMN question_type TYPE questiontype "
        "USING question_type::text::questiontype"
    )
    op.execute("DROP TYPE questiontype_old")

    # --- Part 2: Create the new tables (with the create_type=False fix) ---
    op.create_table('test_templates',
        sa.Column('template_id', sa.String(), nullable=False),
        sa.Column('owner_user_id', sa.String(), nullable=True),
        sa.Column('exam_id', sa.Integer(), nullable=False),
        sa.Column('subject_id', sa.Integer(), nullable=True),
        sa.Column('chapter_id', sa.Integer(), nullable=True),
        sa.Column('template_name', sa.String(), nullable=False),
        sa.Column('test_type', sa.Enum('CHAPTER_TEST', 'SUBJECT_TEST', 'FULL_MOCK', 'CUSTOM', name='testtypeenum', create_type=False), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('duration_minutes', sa.Integer(), nullable=False),
        sa.Column('is_public', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['chapter_id'], ['chapters.chapter_id'], ),
        sa.ForeignKeyConstraint(['exam_id'], ['exams.exam_id'], ),
        sa.ForeignKeyConstraint(['owner_user_id'], ['users.user_id'], ),
        sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ),
        sa.PrimaryKeyConstraint('template_id')
    )
    op.create_table('test_template_questions',
        sa.Column('template_id', sa.String(), nullable=False),
        sa.Column('question_id', sa.String(), nullable=False),
        sa.Column('question_order', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ),
        sa.ForeignKeyConstraint(['template_id'], ['test_templates.template_id'], ),
        sa.PrimaryKeyConstraint('template_id', 'question_id')
    )

    # --- Part 3: Correctly modify the 'tests' table ---
    op.add_column('tests', sa.Column('template_id', sa.String(), nullable=True)) # Changed to nullable=True to avoid issues with existing rows
    op.execute('UPDATE tests SET template_id = (SELECT template_id FROM test_templates LIMIT 1)') # Add a default value if needed, or handle appropriately
    op.alter_column('tests', 'template_id', nullable=False) # Now set it to NOT NULL

    op.create_foreign_key('fk_tests_template_id', 'tests', 'test_templates', ['template_id'], ['template_id'])
    op.drop_column('tests', 'chapter_id')
    op.drop_column('tests', 'subject_id')


def downgrade() -> None:
    """Revert schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tests', sa.Column('chapter_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_tests_template_id', 'tests', type_='foreignkey')
    op.drop_column('tests', 'template_id')
    
    op.drop_table('test_template_questions')
    op.drop_table('test_templates')

    # Revert the ENUM change
    op.execute("ALTER TYPE questiontype RENAME TO questiontype_new")
    op.execute("CREATE TYPE questiontype AS ENUM('MCSC', 'MCMC', 'INT', 'NUM')") # Revert to the old state defined in the first migration
    op.execute(
        "ALTER TABLE questions ALTER COLUMN question_type TYPE questiontype "
        "USING question_type::text::questiontype"
    )
    op.execute("DROP TYPE questiontype_new")
