import json
import os
from thefuzz import process # For fuzzy string matching

# --- Configuration ---
FILE = "2017_1"
SYLLABUS_FILE = "jee_advanced_syllabus.json"
LLM_OUTPUT_FILE = f"llm_outputs/{FILE}.json"
DATABASE_READY_FILE = f"seed_data/{FILE}.json"
SIMILARITY_THRESHOLD = 90 # Confidence score (out of 100) for fuzzy matching

def create_subtopic_lookup_map(syllabus_data):
    """
    Flattens the nested syllabus into a simple dictionary for fast lookups.
    Maps subtopic_name -> subtopic_id.
    """
    lookup_map = {}
    try:
        for subject, chapters in syllabus_data["syllabus"].items():
            for chapter, subtopics in chapters.items():
                for subtopic in subtopics:
                    lookup_map[subtopic["subtopic_name"]] = subtopic["subtopic_id"]
    except KeyError as e:
        print(f"Error: syllabus.json seems to be missing a key: {e}")
    return lookup_map

def main():
    """
    Main function to load LLM-processed data, map subtopic names to IDs
    using exact and fuzzy matching, and save the final database-ready result.
    """
    # 1. Load the syllabus and create the lookup map
    if not os.path.exists(SYLLABUS_FILE):
        print(f"Error: Syllabus file not found at '{SYLLABUS_FILE}'")
        return
    
    with open(SYLLABUS_FILE, 'r') as f:
        syllabus = json.load(f)
    
    subtopic_map = create_subtopic_lookup_map(syllabus)
    if not subtopic_map:
        print("Error: Subtopic lookup map could not be created. Exiting.")
        return
        
    # Get a list of all valid subtopic names for fuzzy matching
    valid_subtopic_names = list(subtopic_map.keys())
    print(f"--- Successfully created a lookup map with {len(subtopic_map)} subtopics. ---")

    # 2. Load the JSON data generated by the LLM
    if not os.path.exists(LLM_OUTPUT_FILE):
        print(f"Error: LLM output file not found at '{LLM_OUTPUT_FILE}'")
        return
        
    with open(LLM_OUTPUT_FILE, 'r') as f:
        llm_questions = json.load(f)
    
    print(f"--- Loaded {len(llm_questions)} questions from the LLM output. ---")
    
    # 3. Process the questions and create the final database-ready list
    database_ready_questions = []
    skipped_questions = []
    fuzzy_corrections = 0

    for q in llm_questions:
        subtopic_name_from_llm = q.get("subtopic_name")
        subtopic_id = None
        
        # Stage 1: Try for a perfect, case-sensitive match (fast and ideal)
        if subtopic_name_from_llm in subtopic_map:
            subtopic_id = subtopic_map[subtopic_name_from_llm]
        
        # Stage 2: If no perfect match, use fuzzy matching as a fallback
        else:
            # Find the best match from the list of valid subtopic names
            best_match, score = process.extractOne(subtopic_name_from_llm, valid_subtopic_names)
            
            if score >= SIMILARITY_THRESHOLD:
                print(f"Info: Corrected '{subtopic_name_from_llm}' to '{best_match}' (Score: {score})")
                subtopic_id = subtopic_map[best_match]
                fuzzy_corrections += 1
        
        # If we found an ID (either exact or fuzzy), process the question
        if subtopic_id:
            db_question = q.copy()
            db_question["subtopic_id"] = subtopic_id
            
            # Clean up fields that are not in the final database schema
            del db_question["subtopic_name"]
            if "subject" in db_question:
                del db_question["subject"]

            database_ready_questions.append(db_question)
        else:
            # If no confident match was found, skip and log for review
            skipped_questions.append(subtopic_name_from_llm)

    # 4. Save the final JSON file and report results
    with open(DATABASE_READY_FILE, 'w') as f:
        json.dump(database_ready_questions, f, indent=2)

    print(f"\n--- Processing complete! ---")
    print(f"✅ Successfully processed and saved {len(database_ready_questions)} questions.")
    print(f"🔧 Corrected {fuzzy_corrections} subtopic names using fuzzy matching.")
    
    if skipped_questions:
        print(f"⚠️ Skipped {len(skipped_questions)} questions due to low-confidence subtopic matches:")
        # Print unique skipped subtopics for easier debugging
        for skipped in sorted(list(set(skipped_questions))):
            print(f"  - '{skipped}'")
    
    print(f"\nFinal database-ready data is in '{DATABASE_READY_FILE}'")


if __name__ == "__main__":
    main()